name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: sh ./.github/workflows/configure.sh
    - name: Build binaries
      run: make
    - name: Archive binaries and header 
      uses: actions/upload-artifact@v4
      with:
        name: latest-linux-bundle
        path: |
          bin
          include
    - name: Upload all files
      run: sh ./.github/workflows/upload.sh
